import { DEFAULT_ATTRIBUTES, type CharacterAttributes, type ClassTemplate } from '@/lib/types';

function stats(values: Partial<CharacterAttributes>): CharacterAttributes {
  return { ...DEFAULT_ATTRIBUTES, ...values };
}

export const CLASS_TEMPLATES: ClassTemplate[] = [
  {
    id: 'class-alchemist',
    key: 'alchemist',
    name: 'Alchemist',
    role: 'Support · Decent sustain',
    armor: 'Light armor',
    identity: 'Intelligent and resourceful seekers of knowledge, renowned for their command of potions and alchemical craft.',
    inventorySlots: 16,
    spellSlots: 2,
    baseHp: 110,
    baseMana: 50,
    attributes: stats({ strength: -1, vitality: -1, intelligence: 1, recovery: 1, alchemy: 5 }),
    passives: ['Once per combat, use or make a potion or alchemical item without spending the main action or movement.', 'Has unlimited flasks and Arcane Nectar while maintaining a house or residence.'],
    tokenColor: '#4d8f83'
  },
  {
    id: 'class-apothecary',
    key: 'apothecary',
    name: 'Apothecary',
    role: 'Support · Great sustain',
    armor: 'Medium armor',
    identity: 'Durable battlefield mages whose restorative support can hold a party together even on the front line.',
    inventorySlots: 15,
    spellSlots: 5,
    baseHp: 130,
    baseMana: 90,
    attributes: stats({ strength: -3, agility: -1, vitality: 1, recovery: 2, accuracy: -1, mana_regen: 2, alchemy: 2, stealth: -2 }),
    passives: ['Can heal an ally for 5 HP in place of movement.'],
    tokenColor: '#5579a8'
  },
  {
    id: 'class-apprentice',
    key: 'apprentice',
    name: 'Apprentice',
    role: 'Hybrid · Decent sustain',
    armor: 'Medium armor',
    identity: 'Naturally talented learners who trade some magical utility for freedom, adaptability, and staying power.',
    inventorySlots: 16,
    spellSlots: 5,
    baseHp: 100,
    baseMana: 75,
    attributes: stats({ agility: 1, vitality: -1, intelligence: 1, mana_regen: 1, alchemy: 1 }),
    passives: ['While paired with a Mage: +1 Intelligence.', 'While paired with a Knight: +1 Strength.', 'While paired with a Ranger: +1 Accuracy. These bonuses can stack.'],
    tokenColor: '#8a6da1'
  },
  {
    id: 'class-armor-clad',
    key: 'armor-clad',
    name: 'Armor-clad',
    role: 'Defense · Great sustain',
    armor: 'Heavy armor',
    identity: 'Relentless front-line warriors who sacrifice speed and subtlety for overwhelming defensive presence.',
    inventorySlots: 10,
    spellSlots: 1,
    baseHp: 165,
    baseMana: 50,
    attributes: stats({ strength: 2, agility: -3, vitality: 3, intelligence: -3, charisma: -1, range: -2, perception: -1, alchemy: 1, stealth: -2 }),
    passives: ['Distribution redirects 50% of a target’s incoming damage to the Armor-clad.', 'Pays only material costs for armor labor.', 'Cannot receive additional defensive bonuses from shields.'],
    tokenColor: '#9a6e52'
  },
  {
    id: 'class-beastmaster',
    key: 'beastmaster',
    name: 'Beastmaster',
    role: 'Hybrid · Poor sustain',
    armor: 'Light armor',
    identity: 'Rare animal handlers whose companions become a force of their own across the battlefield.',
    inventorySlots: 20,
    spellSlots: 1,
    baseHp: 90,
    baseMana: 50,
    attributes: stats({ strength: -3, agility: 1, recovery: 1, charisma: 3, accuracy: 1, perception: 2 }),
    passives: ['Tame is a free spell and uses d6 + Charisma + buffs against a creature’s Wild score.', 'May bring up to 20 Wild score worth of beasts per mission.'],
    tokenColor: '#77875a'
  },
  {
    id: 'class-blacksmith',
    key: 'blacksmith',
    name: 'Blacksmith',
    role: 'Support · Decent sustain',
    armor: 'Medium armor',
    identity: 'Practical craftspeople whose command of tools, weapons, armor, and runes makes them invaluable anywhere.',
    inventorySlots: 18,
    spellSlots: 3,
    baseHp: 125,
    baseMana: 50,
    attributes: stats({ strength: 2, agility: -1, vitality: 1, charisma: 2, range: -2, alchemy: 1, stealth: -1 }),
    passives: ['Pays only material costs for smithing labor.', 'Once per combat, grant a chosen melee weapon +1 Strength until combat or the scene ends.'],
    tokenColor: '#b28b45'
  },
  {
    id: 'class-knight',
    key: 'knight',
    name: 'Knight',
    role: 'Attack · Decent sustain',
    armor: 'Medium armor',
    identity: 'Well-rounded combat experts with political presence, battlefield leadership, and a talent for mounted fighting.',
    inventorySlots: 14,
    spellSlots: 2,
    baseHp: 125,
    baseMana: 25,
    attributes: stats({ strength: 1, vitality: 1, intelligence: -1, charisma: 2, accuracy: 1, range: -1, mana_regen: -2, alchemy: -1 }),
    passives: ['+1 Strength while mounted on a horse.', 'When hit, a parry roll of 18–20 prevents all damage; 15–17 prevents half.'],
    tokenColor: '#a05e5a'
  },
  {
    id: 'class-mage',
    key: 'mage',
    name: 'Mage',
    role: 'Attack · Poor sustain',
    armor: 'Light armor',
    identity: 'Versatile magical heavy-hitters with an answer for nearly every problem—provided they survive long enough to cast it.',
    inventorySlots: 10,
    spellSlots: 10,
    baseHp: 70,
    baseMana: 100,
    attributes: stats({ strength: -3, vitality: -3, intelligence: 3, charisma: 1, range: 1, mana_regen: 1 }),
    passives: ['Regain 10 Mana whenever an enemy is killed with a spell.'],
    tokenColor: '#567a7f'
  },
  {
    id: 'class-mendrunner',
    key: 'mendrunner',
    name: 'Mendrunner',
    role: 'Hybrid · Poor sustain',
    armor: 'Medium armor',
    identity: 'Nimble practitioners of botany and natural medicine who reject magic in favor of hard-won remedies.',
    inventorySlots: 20,
    spellSlots: 0,
    baseHp: 85,
    baseMana: 0,
    attributes: stats({ strength: -1, agility: 3, intelligence: -5, recovery: 3, charisma: -3, accuracy: 1, perception: 3, alchemy: 4, stealth: 1 }),
    passives: ['Heal an ally for 2d6 + Recovery + Alchemy and remove one debuff or negative effect.', 'Immune to poison and illness.'],
    tokenColor: '#6b8f68'
  },
  {
    id: 'class-muscle',
    key: 'the-muscle',
    name: 'The Muscle',
    role: 'Defense · Great sustain',
    armor: 'Medium armor',
    identity: 'Notorious for a large frame and small brains, built to soak punishment and become the group’s blunt-force answer.',
    inventorySlots: 10,
    spellSlots: 1,
    baseHp: 150,
    baseMana: 40,
    attributes: stats({ strength: 3, agility: -1, vitality: 1, intelligence: -3, recovery: 2, charisma: -2, accuracy: -2, range: -2, perception: -1, alchemy: -2, stealth: -2 }),
    passives: ['When The Muscle kills an enemy, gain 1d6 for ensuing damage rolls. Resets after each combat or scene ends. Max of 5d6.'],
    tokenColor: '#9f6540'
  },
  {
    id: 'class-ranger',
    key: 'ranger',
    name: 'Ranger',
    role: 'Attack · Poor sustain',
    armor: 'Light armor',
    identity: 'Back-line attackers and scouts who combine punishing range with reconnaissance and specialized ammunition.',
    inventorySlots: 15,
    spellSlots: 1,
    baseHp: 90,
    baseMana: 50,
    attributes: stats({ strength: -2, agility: 1, vitality: -2, intelligence: 1, accuracy: 2, range: 3, perception: 2, stealth: 1 }),
    passives: ['Can tame birds.', 'Three times per combat, fire three arrows in one draw.', 'May buy and craft elemental or effect-tipped arrows.'],
    tokenColor: '#7c8a49'
  },
  {
    id: 'class-rogue',
    key: 'rogue',
    name: 'Rogue',
    role: 'Attack · Poor sustain',
    armor: 'Light armor',
    identity: 'Cunning duelists who thrive on surprise, isolation, and catching enemies at their most vulnerable.',
    inventorySlots: 16,
    spellSlots: 3,
    baseHp: 90,
    baseMana: 50,
    attributes: stats({ strength: -1, agility: 2, vitality: -1, charisma: -3, perception: 3, alchemy: 1, stealth: 3 }),
    passives: ['Backstab deals double damage from behind, from stealth, or against a pinned or defenseless target.', 'May use Agility instead of Strength for attacks that trigger Backstab.'],
    tokenColor: '#6b617e'
  },
  {
    id: 'class-sage',
    key: 'sage',
    name: 'Sage',
    role: 'Support · Poor sustain',
    armor: 'Medium armor',
    identity: 'Selfless support casters whose mastery of recovery turns a single act of healing into aid for the whole party.',
    inventorySlots: 12,
    spellSlots: 5,
    baseHp: 70,
    baseMana: 100,
    attributes: stats({ strength: -2, agility: 2, vitality: -2, intelligence: -5, recovery: 3, charisma: 2, accuracy: -2, mana_regen: 2 }),
    passives: ['Healing and enhancement spells use Recovery instead of Intelligence for magic rolls.', 'Heals also restore half the amount, rounded up, to another ally or the original target.'],
    tokenColor: '#7581a0'
  },
  {
    id: 'class-talismanist',
    key: 'talismanist',
    name: 'Talismanist',
    role: 'Attack · Decent sustain',
    armor: 'Medium armor',
    identity: 'Rune-armed warriors who bind magic into weapons and armor, turning every piece of gear into a spell vessel.',
    inventorySlots: 10,
    spellSlots: 0,
    baseHp: 125,
    baseMana: 100,
    attributes: stats({ strength: 1, vitality: 1, intelligence: 1, accuracy: 1, alchemy: -1, stealth: -2 }),
    passives: ['Begins with three random low-level runes.', 'Each spell-infused weapon on hand can cast its spell twice per combat.'],
    tokenColor: '#926d9f'
  },
  {
    id: 'class-warden',
    key: 'warden',
    name: 'Warden',
    role: 'Hybrid · Decent sustain',
    armor: 'Medium armor',
    identity: 'Jack-of-all-trades survivalists with broad usefulness, cunning instincts, and flexible party support.',
    inventorySlots: 20,
    spellSlots: 3,
    baseHp: 110,
    baseMana: 75,
    attributes: stats({ charisma: -2, perception: 2, alchemy: 1 }),
    passives: ['Once per combat or exploration scene, reroll a failed Perception, Alchemy, Survival, or Utility check.', 'Gains a +2 modifier of choice in a single category where the party has no bonuses.'],
    tokenColor: '#79895f'
  }
];

export const DEFAULT_CLASS_TEMPLATE = CLASS_TEMPLATES[0];
